version: "3"
services:
  fastapi:
    build:
      context: backend
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  react:
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
volumes:
  postgres_data:
